In [1]:
# Downloading the data

import kaggle

kaggle.api.authenticate()  # To use the api, a kaggle.json file is necessary for authentication information. For more info: https://www.kaggle.com/docs/api

kaggle.api.dataset_download_files(  # Downloads a dataset given the slug for owner/dataset_name, unzip=True unzips files on download, path is specified to ./mushroom_data
    "alicemtopcu/top-1500-games-on-steam-by-revenue-09-09-2024", unzip=True, path="top_steam_data"
)

Dataset URL: https://www.kaggle.com/datasets/alicemtopcu/top-1500-games-on-steam-by-revenue-09-09-2024

In [6]:
# Reading into DataFrame
import pandas as pd
from IPython.display import HTML

top_steam_games = pd.read_csv('top_steam_data/Steam_2024_bestRevenue_1500.csv')

# Borrowing tidier from previous assignment
def horizontal(dfs):
    html = '<div style="display:flex">'
    for df in dfs:
        html += '<div style="margin-right: 32px">'
        html += df.to_html()
        html += "</div>"
    html += "</div>"
    display(HTML(html))

display(top_steam_games.head())
object_cols = top_steam_games.select_dtypes(include=['object']).columns
horizontal([top_steam_games.describe(), top_steam_games[object_cols].describe()])

,name,releaseDate,copiesSold,price,revenue,avgPlaytime,reviewScore,publisherClass,publishers,developers,steamId
0,WWE 2K24,07-03-2024,165301,99.99,8055097.0,42.365140,71,AAA,2K,Visual Concepts,2315690
1,EARTH DEFENSE FORCE 6,25-07-2024,159806,59.99,7882151.0,29.651061,57,Indie,D3PUBLISHER,SANDLOT,2291060
2,Sins of a Solar Empire II,15-08-2024,214192,49.99,7815247.0,12.452593,88,Indie,Stardock Entertainment,"Ironclad Games Corporation,Stardock Entertainment",1575940
3,Legend of Mortal,14-06-2024,440998,19.99,7756399.0,24.797817,76,Indie,"Paras Games,Obb Studio Inc.",Obb Studio Inc.,1859910
4,Shin Megami Tensei V: Vengeance,13-06-2024,141306,59.99,7629252.0,34.258496,96,AA,SEGA,ATLUS,1875830